name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2.1.4
        with:
          path: |
            /opt/sonar-scanner/.sonar
            ~/node_modules
          key: sonar-npm
      - run: |
          npm config set registry http://registry.npmjs.org
          npm install
          npm test
      - env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: sonar-scanner
