name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2.1.4
        with:
          path: |
            /opt/sonar-scanner/.sonar
            ~/node_modules
          key: sonar-npm
      - uses: actions/setup-node@v1
      - run: |
          npm install
          npm test
      - uses: wouter-admiraal-sonarsource/sonarqube-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
